apiVersion: v1
kind: Pod
metadata:
  name: gradle-build-hardened-example
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 185
    runAsGroup: 0
    fsGroup: 0
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: gradle
      image: ubi9-jdk21-gradle8-hardened:8.14.5
      imagePullPolicy: IfNotPresent
      args:
        - --version
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
      volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: tmp
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
    - name: workspace
      emptyDir: {}
